### ISSUE TITLE
What was Needed for Lab 4

### ISSUE THREAD

**Issue by amasciotra** [thomaschristinck/DPM#25]
so..
the robot is able to regardless on any orientation u set it in the corner square, to rotate find the walls and set itself up along the x axis at 0 degrees almost perfectly everytime. 

now to move to the point 0 , 0 (the point where the four lines cross) 
when you press the right button on the brick, the 2nd part should engage.
LIGHTLOCALIZER.class is what takes care of this part (at least i think) and needs the fixing, the other classes all work well
in the doLocalization method it seems to not be working to the best that it can be and should be tuned

we need it to drive straight along the x axis to cross the first line, then stop and rotate 90 to go up the positive y axis until it passes that line, then turn 90 etc and basically make it turn in a square around the 0,0 point clocking the angles at each turn, which i think the code already does and finally cross 0,0, point and stop there. 

*issues, sometimes the robot starts by driving backwards instead of forward.. idk why, maybe manually force the wheels to turn forward by setting the wheels in the if statement to forward.
the light sensor threshold needs to be played with to detect the lines. 

****right now the light sensor is at the front, but maybe we should connect it at the back so when it hits the line, the full robot has passed the line, just my idea. 

dont be afraid to text me il have my phone in quebec lol

**Comment by amasciotra** [comment]
also, i do not quite understand the 2 ways to do the localizer that the instructions say and we have to decide which one is better, like by running 2 different localizer 10 times not quite sure what that means

**Comment by thomaschristinck** [comment]
So far I've touched up the US localizer. It's perfect. The Light Localization isn't great but once I fix a couple bugs I should be able to get it done in a couple of hours

**Comment by amasciotra** [comment]
ok sounds good, did you figure out what they mean by the 10 trials shit we have to do??

**Comment by thomaschristinck** [comment]
The two ways are falling edge and rising edge. You decide which one to use within the code for US localizer

**Comment by amasciotra** [comment]
so we have to do rising edge 10 times and falling edge 10 times ? what's even the difference between each one

**Comment by thomaschristinck** [comment]
Just the method. If you look in the USLocalization code, there's a method for it
